version: '3'

services:
  db:
    image: postgres:14.0
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: poetry run gunicorn main:app --bind 0.0.0.0:8000 --workers=2 --worker-class aiohttp.GunicornWebWorker
    depends_on:
      - db
    environment:
      - API_DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
